include:
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml
  - component: gitlab.com/gl-components/nx-set-shas/nx-set-shas@1.0.1

workflow:
  auto_cancel:
    on_new_commit: conservative

default:
  image: node:20@sha256:a4d1de4c7339eabcf78a90137dfd551b798829e3ef3e399e0036ac454afa1291

variables:
  CI: 'true'
  GIT_DEPTH: 0
  NX_CLOUD_ACCESS_TOKEN: $NX_CLOUD_TOKEN

.node-cache: &node-cache
  key:
    files:
      - package-lock.json
  paths:
    - .npm/
  policy: pull

# Main job
CI:
  interruptible: true
  cache:
    <<: *node-cache
    policy: pull-push
  script:
    # This enables task distribution via Nx Cloud
    # Run this command as early as possible, before dependencies are installed
    # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
    # Connect your workspace by running "nx connect" and uncomment this
    # - npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

    - npm ci --cache .npm --prefer-offline

    # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
    # - npx nx-cloud record -- echo Hello World
    - npx nx-cloud record -- nx format:check --base=$NX_BASE --head=$NX_HEAD
    # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD -t lint test build
